version: '3.8'

services:
  video-processor:
    build: .
    volumes:
      - ./videos:/app/videos
      - ./text:/app/text
      - C:/interview/project/trans-ai/trans-ai/videos:/app/videos
    command: python main.py